import {
  IconContext,
  type Icon as PhosphorIcon,
  Sparkle,
  UsersThree,
  Wallet,
  MapTrifold,
  Compass,
  MusicNotes,
  AirplaneTilt,
  SunHorizon,
  ArrowUpRight,
  ArrowRight,
  ArrowLeft,
  List,
  X,
  Moon,
  Sun,
  Spade,
  Heart,
  Diamond,
  Club,
  MapPin,
  MapPinLine,
  CalendarBlank,
  Clock,
  ListBullets,
  Cards,
  Check,
  CheckCircle,
  Trophy,
  Crown,
  Medal,
  Star,
  Plus,
  Trash,
  GlobeHemisphereWest,
  Camera,
  CaretDown,
  CaretRight,
  Target,
  Fire,
  Ticket,
  Lightning,
  Bed,
  Path,
  GearSix,
  PencilSimple,
  Image as ImageIcon,
  ForkKnife,
  Mountains,
  Confetti,
  Coins,
  ChartLineUp,
  CurrencyDollar,
  NoteBlank,
  Sword,
  SignOut,
  User,
  Info,
  ArrowsClockwise,
  ChatCircleDots,
  Playlist,
  SlidersHorizontal,
  MagnifyingGlass,
  SuitcaseRolling,
  Car,
  PersonSimpleWalk,
  PersonSimpleBike,
  Bus,
  AirplaneTakeoff,
  AirplaneLanding,
  Tag,
  Drop,
  Thermometer,
  Snowflake,
  Cloud,
  CloudSun,
  CloudRain,
  CloudFog,
  CloudSnow,
  CloudLightning,
  Flag,
  LinkSimple,
  ChatText,
  PaperPlaneTilt,
} from '@phosphor-icons/react';
import type { ReactNode } from 'react';

/**
 * Curated Phosphor set, standardized to `light` weight. Import icons from here
 * rather than from `@phosphor-icons/react` directly so weight/size stay uniform.
 */
export const icons = {
  ai: Sparkle,
  collab: UsersThree,
  expense: Wallet,
  map: MapTrifold,
  compass: Compass,
  music: MusicNotes,
  plane: AirplaneTilt,
  paperPlane: PaperPlaneTilt,
  weather: SunHorizon,
  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  menu: List,
  close: X,
  moon: Moon,
  sun: Sun,
  spades: Spade,
  hearts: Heart,
  diamonds: Diamond,
  clubs: Club,
  pin: MapPin,
  pinLine: MapPinLine,
  calendar: CalendarBlank,
  clock: Clock,
  list: ListBullets,
  cards: Cards,
  check: Check,
  checkCircle: CheckCircle,
  trophy: Trophy,
  crown: Crown,
  medal: Medal,
  star: Star,
  plus: Plus,
  trash: Trash,
  globe: GlobeHemisphereWest,
  camera: Camera,
  caretDown: CaretDown,
  caretRight: CaretRight,
  target: Target,
  fire: Fire,
  ticket: Ticket,
  lightning: Lightning,
  bed: Bed,
  path: Path,
  gear: GearSix,
  pencil: PencilSimple,
  image: ImageIcon,
  food: ForkKnife,
  mountains: Mountains,
  confetti: Confetti,
  coins: Coins,
  chart: ChartLineUp,
  dollar: CurrencyDollar,
  note: NoteBlank,
  sword: Sword,
  signOut: SignOut,
  user: User,
  info: Info,
  refresh: ArrowsClockwise,
  chat: ChatCircleDots,
  playlist: Playlist,
  filter: SlidersHorizontal,
  search: MagnifyingGlass,
  suitcase: SuitcaseRolling,
  car: Car,
  walk: PersonSimpleWalk,
  bike: PersonSimpleBike,
  bus: Bus,
  planeTakeoff: AirplaneTakeoff,
  planeLanding: AirplaneLanding,
  tag: Tag,
  drop: Drop,
  thermometer: Thermometer,
  snow: Snowflake,
  cloud: Cloud,
  cloudSun: CloudSun,
  cloudRain: CloudRain,
  cloudFog: CloudFog,
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  flag: Flag,
  link: LinkSimple,
  comment: ChatText,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  size = 20,
  weight,
}: {
  name: IconName;
  size?: number;
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill';
}) {
  const Cmp = icons[name];
  return <Cmp size={size} weight={weight} />;
}

/** Wrap the app once so every Phosphor icon defaults to light weight. */
export function IconProvider({ children }: { children: ReactNode }) {
  return (
    <IconContext.Provider value={{ weight: 'light', size: 20 }}>
      {children}
    </IconContext.Provider>
  );
}
