import { Link } from 'react-router-dom';

const LAST_UPDATED = 'October 4, 2026';
const CONTACT_EMAIL = 'team.voyageapp@gmail.com';

export default function PrivacyPage() {
  return (
    <main className="wrap legal-page">
      <span className="eyebrow">Legal</span>
      <h1>Privacy Policy</h1>
      <p className="legal-updated">Last updated: {LAST_UPDATED}</p>

      <p>
        Voyage ("Voyage", "we", "us") is operated by an individual based in California, United
        States. This policy explains what personal data we collect when you use Voyage, why we
        collect it, who we share it with, and the choices and rights you have over it. If you
        have questions, contact us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>1. Information we collect</h2>
      <p>We collect information you give us directly, and some generated by using the app:</p>
      <ul>
        <li>
          <strong>Account information:</strong> name and email address, and a hashed password if
          you sign up with email. If you sign up or log in with Google, we receive your name,
          email, and Google account ID from Google — we never see or store your Google password.
        </li>
        <li>
          <strong>Profile information:</strong> anything you optionally add, such as a bio,
          avatar image, or a travel wishlist.
        </li>
        <li>
          <strong>Trip content:</strong> trips, itinerary items, notes, locations and
          coordinates, dates, budgets, expenses, hotel and flight details you enter, playlists,
          and photos you upload to a trip log.
        </li>
        <li>
          <strong>Photos:</strong> images you upload are sent directly from your browser to our
          image-hosting provider, Cloudinary; we store only the resulting URL. If a photo
          contains embedded location data (EXIF geotags), our app reads that data in your browser
          to offer to tag the photo's location — it is only saved to your trip if you choose to
          apply it.
        </li>
        <li>
          <strong>Gamification activity:</strong> sidequest claims, completions, comments, event
          enrollments, XP, and badges.
        </li>
        <li>
          <strong>Public content:</strong> if you mark a trip as public, or participate in public
          sidequests, that content (and your name/profile) becomes visible to other users and, in
          the case of a share link, to anyone with the link.
        </li>
        <li>
          <strong>AI chat messages:</strong> messages you send to the in-app trip-planning
          assistant, which are processed by our AI provider, Anthropic, to generate a response.
        </li>
        <li>
          <strong>Payment information:</strong> if you subscribe to a paid plan, payment is
          handled entirely by Stripe. We receive and store your subscription status and Stripe
          customer ID — never your card number.
        </li>
        <li>
          <strong>Technical data:</strong> standard information inherent to web requests, such as
          your IP address and browser user agent, generated as you use the app.
        </li>
      </ul>

      <h2>2. How we use this information</h2>
      <ul>
        <li>To provide the core service: create and sync your trips, itineraries, and sidequest progress.</li>
        <li>To authenticate you and keep your account secure.</li>
        <li>To process payments and manage subscriptions.</li>
        <li>To power optional features you choose to use: the AI trip assistant, map and location lookups, weather and transit info, and Spotify playlist export.</li>
        <li>To send account-related email, such as sign-in verification codes and trip collaboration invites.</li>
        <li>To diagnose bugs and keep the service reliable and secure.</li>
      </ul>
      <p>We do not sell your personal information, and we do not use your trip content to train AI models.</p>

      <h2>3. Who we share data with</h2>
      <p>
        We share data only with the service providers that help us run Voyage, each of which
        processes data on our behalf under their own terms:
      </p>
      <ul>
        <li><strong>Google</strong> — for sign-in, and for maps, places, and geocoding features.</li>
        <li><strong>Anthropic</strong> — processes messages you send to the AI trip assistant.</li>
        <li><strong>Stripe</strong> — processes payments for paid plans.</li>
        <li><strong>Cloudinary</strong> — hosts photos you upload.</li>
        <li><strong>Spotify</strong> — if you choose to export a trip playlist, we use a temporary authorization to create it in your own Spotify account.</li>
        <li><strong>Resend</strong> — delivers transactional emails (verification codes, invites) on our behalf.</li>
        <li><strong>MongoDB Atlas, Render, and Vercel</strong> — host our database, server, and web app.</li>
      </ul>
      <p>
        We may also disclose information if required by law, or to protect the rights, safety,
        or property of Voyage, our users, or the public.
      </p>

      <h2>4. Public and shared content</h2>
      <p>
        Trips you mark public, and public sidequest activity (claims, completions, photos,
        comments), are visible to other Voyage users on the Discover feed and leaderboards. Trip
        share links grant read-only access to anyone who has the link, whether or not they have
        a Voyage account. Think about what you make public or share.
      </p>

      <h2>5. Data retention</h2>
      <p>
        We keep your account and trip data for as long as your account is active. If you delete
        your account, we delete your personal data and trip content within a reasonable period,
        except where we are required to retain limited records (for example, payment records) for
        legal or accounting purposes.
      </p>

      <h2>6. Your rights and choices</h2>
      <p>
        You can access and update most of your information directly in your account settings and
        profile. You can also contact us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>{' '}
        to request a copy of your data, or to have your account and associated data deleted.
      </p>
      <p>
        <strong>If you are in the European Economic Area or United Kingdom (GDPR):</strong> you
        have the right to access, correct, delete, restrict or object to our processing of your
        personal data, and to receive your data in a portable format. Where we rely on your
        consent (for example, optional AI or location features), you can withdraw it at any time.
        Our legal bases for processing are: performance of our contract with you (providing the
        service you signed up for), your consent (for optional features), and our legitimate
        interests (such as securing the service and preventing abuse). You also have the right to
        lodge a complaint with your local data protection authority.
      </p>
      <p>
        <strong>If you are a California resident (CCPA/CPRA):</strong> you have the right to know
        what personal information we collect and how it's used, to request deletion, and to
        non-discrimination for exercising these rights. We do not sell or "share" personal
        information as those terms are defined under California law.
      </p>

      <h2>7. Security</h2>
      <p>
        We use industry-standard measures to protect your data, including password hashing,
        encrypted connections (HTTPS), and signed authentication tokens. No system is perfectly
        secure, and we cannot guarantee absolute security of information you transmit to us.
      </p>

      <h2>8. Children's privacy</h2>
      <p>
        Voyage is not directed at children, and is not intended for use by anyone under 16. We do
        not knowingly collect personal information from children under 16. If you believe a child
        has provided us with personal data, contact us and we will delete it.
      </p>

      <h2>9. International data transfers</h2>
      <p>
        Voyage is operated from the United States, and our service providers may process data in
        the United States or other countries. By using Voyage, you understand that your
        information may be transferred to and processed in countries outside your own, which may
        have different data protection laws.
      </p>

      <h2>10. Changes to this policy</h2>
      <p>
        We may update this policy as the app evolves. If we make material changes, we'll update
        the "last updated" date above and, where appropriate, notify you directly.
      </p>

      <h2>11. Contact us</h2>
      <p>
        Questions about this policy or your data? Email{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. See also our{' '}
        <Link to="/terms">Terms of Service</Link>.
      </p>
    </main>
  );
}
